### ISSUE TITLE
Error whith a Git LFS enabled repository

### ISSUE THREAD

**Issue by art049** [tiangolo/latest-changes#40]
Hi, thanks for the action, makes things way easier :smile: .

When used with a repository containing LFS files, an error happens:
```
[master e3dc473] 📝 Update release notes
 1 file changed, 1 insertion(+)
This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.

INFO:root:Pushing changes: CHANGELOG.md

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.

error: failed to push some refs to 'https://github.com/art049/odmantic'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/latest_changes/__main__.py", line 88, in <module>
    subprocess.run(["git", "push"], check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'push']' returned non-zero exit status 1.
```

I'm currently using a workaround to remove the LFS hooks before running the action:
```yaml
      - name: Disable LFS hooks
        run: rm .git/hooks/post-commit .git/hooks/pre-push
```

**Comment by tiangolo** [comment]
I just made a new GitHub App to replace this GitHub Action: https://github.com/tiangolo/latest-changes-app

As it uses the GitHub API directly instead of git, I think that would solve this use case. 🚀
