### ISSUE TITLE
WE HAVE A PURGE ISSUE 

### ISSUE THREAD

**Issue by KVROHITH098** [tiangolo/latest-changes#44]
WE ARE UNABLE TO PURGE THE TO FILES TOGETHER WE NEED HELP THI IS PRIORITY 1.

**Comment by KVROHITH098** [comment]
this is the issue. 


[master e3dc473] 📝 Update release notes
 1 file changed, 1 insertion(+)
This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.

INFO:root:Pushing changes: CHANGELOG.md

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.

error: failed to push some refs to 'https://github.com/art049/odmantic'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/latest_changes/__main__.py", line 88, in <module>
    subprocess.run(["git", "push"], check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'push']' returned non-zero exit status 1.

**Comment by KVROHITH098** [comment]
@tiangolo please help with this fix.
